apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - certificate-eu-patch.yaml
  - ingress-eu-patch.yaml
  - ingressroute-eu-patch.yaml
