apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foobar-api-cert
  namespace: default
spec:
  secretName: foobar-api-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - newyork-cluster.45.77.154.12.nip.io
