apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - certificate-us-patch.yaml
  - ingress-us-patch.yaml
  - ingressroute-us-patch.yaml
