apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - deployment.yaml
  - ingress.yaml
  - ingressroute.yaml
  - service.yaml

images:
  - name: sjc.vultrcr.com/globalregistry/foobar-api
    newTag: latest
